vim.cmd'aunmenu PopUp'
vim.cmd'vnoremenu <silent> PopUp.Cut "+x'
vim.cmd'vnoremenu <silent> PopUp.Copy "+y'
vim.cmd'anoremenu <silent> PopUp.Paste "+gP'
vim.cmd'vnoremenu <silent> PopUp.Paste "+P'
vim.cmd'vnoremenu <silent> PopUp.Delete "_x'
vim.cmd'nnoremenu <silent> PopUp.Select\\ All ggVG'
vim.cmd'vnoremenu <silent> PopUp.Select\\ All gg0oG$'
vim.cmd'inoremenu <silent> PopUp.Select\\ All <C-Home><C-O>VG'
vim.cmd'nnoremenu <silent> PopUp.-1- <Nop>'
vim.cmd'inoremenu <silent> PopUp.-1- <Nop>'
vim.cmd'nnoremenu <silent> PopUp.Toggle\\ Indentline :IndentBlanklineToggle!<CR>'
vim.cmd'inoremenu <silent> PopUp.Toggle\\ Indentline <C-o>:IndentBlanklineToggle!<CR>'
vim.cmd'nnoremenu <silent> PopUp.Toggle\\ Virtual\\ Text :Virtual<CR>'
vim.cmd'inoremenu <silent> PopUp.Toggle\\ Virtual\\ Text <C-o>:Virtual<CR>'
vim.cmd'nnoremenu <silent> PopUp.-2- <Nop>'
vim.cmd'inoremenu <silent> PopUp.-2- <Nop>'
vim.cmd'nnoremenu <silent> PopUp.Code\\ Actions :lua vim.lsp.buf.code_action()<CR>'
vim.cmd'vnoremenu <silent> PopUp.Code\\ Actions :lua vim.lsp.buf.code_action()<CR>'
vim.cmd'inoremenu <silent> PopUp.Code\\ Actions <C-o>:lua vim.lsp.buf.code_action()<CR>'
vim.cmd'nnoremenu <silent> PopUp.Search\\ References :lua vim.lsp.buf.references()<CR>'
vim.cmd'inoremenu <silent> PopUp.Search\\ References <C-o>:lua vim.lsp.buf.references()<CR>'
vim.cmd'nnoremenu <silent> PopUp.Go\\ To\\ Definition :lua vim.lsp.buf.definition()<CR>'
vim.cmd'inoremenu <silent> PopUp.Go\\ To\\ Definition <C-o>:lua vim.lsp.buf.definition()<CR>'
vim.cmd'nnoremenu <silent> PopUp.Information :lua vim.lsp.buf.hover()<CR>'
vim.cmd'inoremenu <silent> PopUp.Information <C-o>:lua vim.lsp.buf.hover()<CR>'
