require('core.plugins')
require('core.settings')
require('core.keymaps')
require('plugin-config.lualine')
require('plugin-config.key-menu')
require('plugin-config.cmp')
require('plugin-config.dashboard')
require('plugin-config.mason')
